name: NestJS Baota Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22        # 22 LTS，24 尚未稳定
          cache: 'npm'

      - name: Install dependencies and Build
        run: |
          npm ci
          npm run build

      - name: Deploy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          target: /www/wwwroot/cms
          source: "dist/,public/,package.json,package-lock.json,ecosystem.config.js"
          overwrite: true

      - name: Restart service on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /www/wwwroot/cms
            npm install --production
            pm2 restart ecosystem.config.js || pm2 start ecosystem.config.js
            pm2 save
